CREATE TABLE IF NOT EXISTS student_scores (
  id INT AUTO_INCREMENT PRIMARY KEY,
  student_id INT NOT NULL,
  class_id INT NULL,
  subject_id INT NOT NULL,
  school_year_id INT NOT NULL,
  semester_id INT NOT NULL,
  score_value DECIMAL(5,2) NULL,
  achievement_note TEXT NULL,
  extracurricular_activity VARCHAR(150) NULL,
  extracurricular_predicate VARCHAR(50) NULL,
  attendance_sick INT NULL,
  attendance_permit INT NULL,
  attendance_absent INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_student_score_period (student_id, subject_id, school_year_id, semester_id),
  INDEX idx_student_scores_student_period (student_id, school_year_id, semester_id),
  INDEX idx_student_scores_subject (subject_id),
  CONSTRAINT fk_student_scores_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_student_scores_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE SET NULL,
  CONSTRAINT fk_student_scores_subject FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE,
  CONSTRAINT fk_student_scores_school_year FOREIGN KEY (school_year_id) REFERENCES school_years(id) ON DELETE CASCADE,
  CONSTRAINT fk_student_scores_semester FOREIGN KEY (semester_id) REFERENCES semesters(id) ON DELETE CASCADE
);
