CREATE TABLE IF NOT EXISTS olympiad_recommendation_feedback (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  subject_id INT NOT NULL,
  student_id INT NOT NULL,
  class_id INT NULL,
  school_year_id INT NULL,
  semester_id INT NULL,
  academic_score DECIMAL(5,2) NOT NULL,
  achievement_score DECIMAL(5,2) NOT NULL,
  recommendation_score DECIMAL(5,2) NOT NULL,
  selected_by_school TINYINT(1) NOT NULL DEFAULT 0,
  outcome_label TINYINT(1) NULL,
  notes TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_orf_subject_created (subject_id, created_at),
  INDEX idx_orf_student (student_id, created_at),
  INDEX idx_orf_outcome (subject_id, outcome_label),
  CONSTRAINT fk_orf_subject FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE,
  CONSTRAINT fk_orf_student FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
  CONSTRAINT fk_orf_class FOREIGN KEY (class_id) REFERENCES classes(id) ON DELETE SET NULL,
  CONSTRAINT fk_orf_school_year FOREIGN KEY (school_year_id) REFERENCES school_years(id) ON DELETE SET NULL,
  CONSTRAINT fk_orf_semester FOREIGN KEY (semester_id) REFERENCES semesters(id) ON DELETE SET NULL
);
